---
title: "R Notebook - Fitting GEF nucleaotide exchange Trp FRET assay with photobleaching"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
# import libraries
library(tidyverse)
library(minpack.lm)
```

```{r, message=FALSE}
# read in data
inputfilename <- "biotek_test_exp/data/good_data_parsed.txt"
biotek.data <- read_delim(inputfilename, delim = "\t", col_names = T)
```

```{r}
run_nls <- function(data, background_type, deadtime) {
  c0 <- data$conc[1]
  GEF_conc <- data$GEF_conc[1]
  print(unique(data$condition))
  #### add the (estimated) dead time
  if (deadtime > 0) {
    deadtime_timepoints <- seq(-1*(deadtime), -5, 5)
    timepoints_to_append <- data[1:length(deadtime_timepoints),]
    timepoints_to_append$Time <- deadtime_timepoints
    timepoints_to_append$observed <- NA
    data <- rbind(data, timepoints_to_append)
  }
  ##### fit the curves in fluorescence units (assuming that the background (photobleaching) is either linear or exponential)
  if (background_type == 'linear') {
    max.f <- max(data$observed, na.rm = T)
    min.f <- min(data$observed, na.rm = T)
    start <- list(f0 = max(data$observed, na.rm = T), k = 0.01, f_plateau = min.f, k_background = 0)
    out <- nlsLM(observed ~ (f0 - f_plateau) * exp(-k * Time) + f_plateau + k_background * Time,
               data = data, start = start, control = nls.lm.control(maxiter = 200))
    f0 <- coef(out)[1]
    k <- coef(out)[2] #### k when signal is in fluorescence units
    f_plateau <- coef(out)[3]  ## plateau in fluorescence units
    k_background <- coef(out)[4]  ## k of bacground fluorescence decay (photobleaching)
    
    data$predicted <- (f0 - f_plateau) * exp(-k * data$Time) + f_plateau + k_background * data$Time
    data$signal <- (f0 - f_plateau) * exp(-k * data$Time) + f_plateau
    data$background <- f_plateau + k_background * data$Time
    data$k_background <- k_background
  }
  
  if  (background_type == 'exponential') {
    #print(unique(data$condition))
    max.f <- max(data$observed, na.rm = T)
    min.f <- min(data$observed, na.rm = T)
    start <- list(span = (max.f - min.f), spanb = (max.f - min.f)/100, k = 0.01, 
                  f_plateau = min.f, k_background = 0.0001)
    out <- nlsLM(observed ~ span * exp(-k * Time) + spanb * exp(-k_background * Time) + f_plateau,
               data = data, start = start, control = nls.lm.control(maxiter = 500))
    span <- coef(out)[1]
    spanb <- coef(out)[2]
    k <- coef(out)[3]
    f_plateau <- coef(out)[4]
    k_background <- coef(out)[5]
    f0 <- span + spanb + f_plateau
    data$predicted <- span * exp(-k * data$Time) + spanb * exp(-k_background * data$Time) + f_plateau
    data$signal <- (f0 - f_plateau) * (exp(-k * data$Time)) + f_plateau
    data$background <- (f0 - f_plateau) * exp(-k_background * data$Time) + f_plateau
    data$k_background <- k_background
  }
  
  if  (background_type == 'none') {
    #print(unique(data$condition))
    start <- list(f0 = max(data$observed, na.rm = T), k = 0.01, f_plateau = 0)
    out <- nlsLM(observed ~ (f0 - f_plateau) * exp(-k * Time),
               data = data, start = start, control = nls.lm.control(maxiter = 300))
    f0 <- coef(out)[1]
    k <- coef(out)[2]
    f_plateau <- coef(out)[3]

    data$predicted <- (f0 - f_plateau) * exp(-k * data$Time)
    data$signal <- (f0 - f_plateau) * (exp(-k * data$Time)) + f_plateau
  }
  
  data$f0 <- f0
  data$k <- k
  data$f_plateau <- f_plateau
  data$vf0 = (f0 * k * exp(k * 0)) / (GEF_conc*0.001)   ### initial rate in fluorescence units
  

  data$v0 <- (c0 * k * exp(k * 0)) / (GEF_conc*0.001)   ## initial rate in concentration units
  return(data)
}
```

```{r}
plot_data <- function(data, background_type, units) {
  
  sink('/dev/null')
  # plot data with fitted curves
  plots <- list()
  conditions = unique(data$condition)
  for (i in seq_along(conditions)) {
    data_to_plot <- data %>% filter(condition == conditions[i])
    plots[[i]] <- ggplot(data_to_plot, mapping = aes(x = Time, y = observed)) + geom_point() +
      geom_line(aes(x = Time, y = predicted), color = "red") +
      geom_line(aes(x = Time, y = signal), color = "green") +
      geom_line(aes(x = Time, y = background), color = "blue") +
      ggtitle(conditions[i])
  }
  pdf(paste(Sys.Date(), background_type, units, 'data.pdf', sep= '_'), width = 12)
  print(plots)
  dev.off()

  # plot michaelis-menten points for exp and lin decay
  plots <- list()
  samples = unique(data$sample)
  for (i in seq_along(samples)) {
    data_to_plot <- data %>% filter(sample == samples[i])
    plots[[i]] <- ggplot(data_to_plot, mapping = aes(x = conc, y = v0, color = as.character(date))) + geom_point() +
      ggtitle(samples[i])
  }
  pdf(paste(Sys.Date(), background_type, units, 'MM.pdf', sep = '_'), width = 12)
  print(plots)
  dev.off()

  # plot parameters for each fit
  pdf(paste(Sys.Date(), background_type, units, 'params.pdf', sep= '_'))
  hist(unique(data$f0), breaks = 100)
  hist(unique(data$k), breaks = 100)
  hist(unique(data$f_plateau), breaks = 100)
  hist(unique(data$vf0), breaks = 100)
  hist(unique(data$vf0), breaks = 100)
  if ( ! (background_type == 'none' | background_type == "cutoff")) {
    hist(unique(data$k_background), breaks = 100)
    print(ggplot(data, aes(x = conc, y = k_background, color = sample)) + geom_point())
  }
  dev.off()

  #return(data)
}
```
```{r}
# fit_MM <- function(data) {
#   #function(pars, xx) (conc * pars$Vmax) / (pars$Km + conc)
#   start <- list(Vmax = 5, Km = 2)
#   out <- nlsLM(v0 ~ (conc * Vmax) / (Km + conc),
#              data = data, start = start, control = nls.lm.control(maxiter = 200))
#   Vmax<- coef(out)[1]
#   Km <- coef(out)[2]
#   kcat <- Vmax
#   data$predicted_v0 <- (data$conc * Vmax) / (Km + data$conc)
#   data$kcat <- kcat
#   data$Km <- Km
#   return(data)
# }
```

```{r}
# Run data assuming photobleaching decay is exponential, first in fluorescence units, then in concentration units
data.exp <- biotek.data
data.exp <- data.exp %>%
  mutate(observed = fluorescence) %>%
  group_by(condition, GEF_conc) %>%
  do(run_nls(., background_type = 'linear', deadtime = 18))
plot_data(data.exp, background_type = 'linear', units = 'fluor')
data.exp <- data.exp %>% 
  mutate(observed = conc - conc*(f0 - signal)/(f0 - f_plateau)) %>%
  do(run_nls(., background_type = 'none', deadtime = 0))
plot_data(data.exp, background_type = 'exponential', units = 'conc')


#MM.data <- data.exp %>%
 # group_by(sample) %>%
  #select(v0, conc) %>%
  #unique() %>%
  #do(fit_MM(.))
```

```{r}
# Run data assuming photobleaching decay is linear, first in fluorescence units, then in concentration units
data.lin <- biotek.data
data.lin <- data.lin %>%
  group_by(condition, conc) %>%
  mutate(observed = fluorescence) %>%
  do(run_nls(., background_type = 'linear', deadtime = 20, c0 = conc))
plot_data(data.exp, background_type = 'linear', units = 'fluor')
data.exp <- data.exp %>% 
  mutate(observed = conc - conc*(max.fluorescence - signal)/(max.fluorescence - min.fluorescence)) %>%
  do(run_nls(., background_type = 'none', deadtime = 0))
plot_data(data.exp, background_type = 'linear', units = 'conc')
```

```{r}
# Run data ignoring photobleaching and using cutoff time, first in fluorescence units, then in concentration units
data.nodecay <- biotek.data
data.nodecay <- data.nodecay %>%
  group_by(condition) %>%
  mutate(relevant = ifelse(Time < cutoff_time, "relevant", "discarded")) %>%
  filter(relevant == "relevant") %>%
  mutate(observed = fluorescence) %>%
  do(run_nls(., background_type = 'cutoff', deadtime = 20)) %>%
  plot_data(background_type = 'cutoff', units = 'fluor') %>%
  mutate(observed = conc - conc*((max(fluorescence, na.rm = T) - fluorescence)/(max(fluorescence, na.rm = T) - min.fluorescence))) %>%
  do(run_nls(., background_type = 'none', deadtime = 0)) %>%
  plot_data(background_type = 'none', units = 'conc')
```
